spring:
  datasource:
    url: jdbc:mysql://localhost:3306/system?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: 19980312a.
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    password: foobared
  aop:
    auto: true
logging:
  level:
    cn.loverot: trace
