spring:
  datasource:
    url: jdbc:mysql://localhost:3306/febs?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  level:
    cn.loverot: trace
